name: blocx
description: BLoC pattern implementation which help with reducing boilerplate which comes with writing traditional BLoC pattern.
version: 0.1.0
author: Haris Kovačević <programmerguy92@gmail.com>
homepage: https://github.com/harisk92/blocx/

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  rxdart: ^0.20.0

